version: '3'
services:
    web:
      image: openhistoricalmap/web:0.0.1-n162.h1341fea
      # image: osmseed-openstreetmap-website:v1
      # build:
      #   context: ./images/web
      #   dockerfile: Dockerfile
      ports:
        - "80:80"
      env_file:
        - ./.env
      depends_on:
        - db
      command: >
        /bin/bash -c "sleep 300000"
        /var/www
      volumes:
          - ./ohm-website:/var/www
      working_dir: /var/www

    db:
      image: osmseed-db:v1
      build:
        context: ./images/db
        dockerfile: Dockerfile
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      env_file:
        - ./.env
  